version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:3000"
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules # 1. 命名卷
    environment:
      - DATABASE_URL=postgresql://admin:attendance_pass@db:5432/attendance_system?schema=public
      - PORT=3000
      - TZ=Asia/Tokyo
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app # 2. 扩大同步范围
      - frontend_node_modules:/app/node_modules # 3. 命名卷
    environment:
      # 重要：这里必须改成您电脑的真实局域网 IP，手机才能访问接口
      # 示例: http://192.168.1.100:4000
      # - VITE_API_URL=http://localhost:4000
      - VITE_API_URL=http://192.168.100.79:4000
      - TZ=Asia/Tokyo
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=attendance_pass
      - POSTGRES_DB=attendance_system
      - TZ=Asia/Tokyo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=Asia/Tokyo
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

# 4. 在底部统一声明
volumes:
  postgres_data:
  backend_node_modules: # 声明后端依赖卷
  frontend_node_modules: # 声明前端依赖卷
  pgadmin_data: # 声明 pgAdmin 数据卷
